version: "3"
services:
  jenkins:
    build: .
    container_name: "jenkins"
    ports: 
      - 8082:8080
      - 5050:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  sonarqube:
    container_name: "sonarqube"
    image: "sonarqube"
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions

      