version: "3.4"
services:
  jenkins:
    container_name: "jenkins"
    image: "jenkins/jenkins:lts"
    ports: 
      - 8082:8080
      - 5050:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - payara_deploy:/var/jenkins_home/workspace/twatter_master/target
  sonarqube:
    container_name: "sonarqube"
    image: "sonarqube"
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
     - MYSQL_ROOT_PASSWORD=root
    volumes: 
     - ./database:/var/lib/mysql
  backend:
    build: .
    container_name: backend
    ports:
     - 8080:8080
     - 4848:4848
     - 8181:8181
     - 9009:9009
    volumes:
     - payara_deploy:/opt/payara/deployments
    links:
     - "db:db"
    depends_on:
     - db
volumes:
  payara_deploy:
    name: payara_deploy
    driver: local
    external: true